version: '3'
services:
  ashal_market_bot:
    build:
      context: '.'
    restart: unless-stopped
    volumes:
      - ./log/:/home/ashal_market_bot/log
      - ./data/:/home/ashal_market_bot/data
    logging:
      options:
        max-size: 50m
